export const selectors = {
    signinPageBtn: 'a.login',
    createAccountEmailField: '#email_create',
    signinEmailField: '#email',
    singinPasswordField: '#passwd',
    signinSubmitBtn: '#SubmitLogin',
    createAccountSubmitEmailBtn: '#SubmitCreate',
    genderRadio: '#id_gender',
    firstNameField: '#customer_firstname',
    lastNameField: '#customer_lastname',
    emailField: '#email',
    passwordField: '#passwd',
    daySelect: '#days',
    monthSelect: '#months',
    yearSelect: '#years',
    newsLetterCheck: '#newsletter',
    submitAccountBtn: '#submitAccount',
    createAccountForm: 'form#account-creation_form',
    accountCreatedMessage: 'p.alert-success',
    createAccountErrorMessage: '#create_account_error',
    emailFormFieldErrorMessage: 'div#center_column > div > ol > li',
    formFieldsErrorMessages: 'div#center_column > div > ol',
    signinErrorMessage: 'div#center_column > div > ol > li',
    loggedInAreaTitle: 'h1.page-heading'
}